# Generated by Django 3.1.6 on 2021-04-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_profile_studentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='images',
        ),
    ]
