# Generated by Django 3.1.6 on 2021-04-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210410_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='images',
            new_name='image',
        ),
    ]
